# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '\u4f5c\u8005', 'verbose_name_plural': '\u4f5c\u8005'},
        ),
        migrations.AlterModelOptions(
            name='authordetail',
            options={'verbose_name': '\u4f5c\u8005\u8be6\u60c5', 'verbose_name_plural': '\u4f5c\u8005\u8be6\u60c5'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '\u4e66\u7c4d', 'verbose_name_plural': '\u4e66\u7c4d'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '\u51fa\u7248\u793e', 'verbose_name_plural': '\u51fa\u7248\u793e'},
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='address',
            field=models.CharField(max_length=50, verbose_name='\u4f4f\u5740'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.Author', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateField(verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='sex',
            field=models.BooleanField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='demo.Author', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='\u51fa\u7248\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Publisher', verbose_name='\u51fa\u7248\u793e'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u4e66\u540d'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=50, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(max_length=60, verbose_name='\u5e02'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(max_length=50, verbose_name='\u56fd\u5bb6'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(max_length=30, verbose_name='\u7701'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(verbose_name='\u7f51\u5740'),
        ),
    ]
